apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-stadistics
  labels:
    app: api-stadistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-stadistics
  template:
    metadata:
      labels:
        app: api-stadistics
    spec:
      containers:
        - image: 'darnack/apistadistics:dev'
          name: api-stadistics
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ASPNETCORE_HTTPS_PORTS
              value: "8081"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "10m"
              memory: "200Mi"
            limits:
              cpu: "100m"
          startupProbe:
            httpGet:
              path: /health/check
              port: 8080
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /health/check
              port: 8080