apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-stadistics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-stadistics
  behavior:
    scaleDown:
        stabilizationWindowSeconds: 180
  minReplicas: 1 # Definimos 2, para tener buena disponibilidad y a los pods le colocamos los recursos necesarios para atender el horario valle
  maxReplicas: 2 # Máximo el doble, en tanto la demanda no crezca mas se prioriza contener el costo
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
