apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-stadistics
  labels:
    app: api-stadistics
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: api-stadistics
  template:
    metadata:
      labels:
        app: api-stadistics
    spec:      
      containers:
        - image: "darnack/apistadistics:3dea008ea0d294ddb009b131892c890e198ce2f1"
          name: api-stadistics
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
              #- name: ASPNETCORE_HTTPS_PORTS
              #  value: "8081"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "10m"
              memory: "200Mi"
            limits:
              cpu: "100m"
