apiVersion: v1
kind: Service
metadata:
  name: api-stadistics
spec:
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 8989
      targetPort: 8080
  selector:
    app: api-stadistics
  