apiVersion: argoproj.io/vlalpha1
kind: Application
metadata:
    name: api-stadistics
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/darnack/apistadistics.chart.git
        path: "."
        targetRevision: HEAD
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
    destination:
        server: https://kubernetes.default.svc
        namespace: demo
I